name: portfolio_workspace
repository: https://github.com/siesdart/jaspr-portfolio

command:
  bootstrap:
    hooks:
      pre: |
        melos install:node
  clean:
    hooks:
      pre: |
        melos clean:jaspr

packages:
  - apps/**
  - packages/**

scripts:
  build:
    packageFilters:
      scope: [portfolio]
    exec: jaspr build --sitemap-domain https://siesdart.fly.dev && npm run build
  build:dart:
    packageFilters:
      dependsOn: build_runner
    exec: dart run build_runner build --delete-conflicting-outputs
  clean:jaspr:
    packageFilters:
      scope: [portfolio]
    exec: jaspr clean
  install:node:
    packageFilters:
      scope: [portfolio]
    exec: npm install
  outdated:
    exec: dart pub outdated --up-to-date --no-dependency-overrides --no-transitive
  upgrade:
    exec: dart pub upgrade --major-versions && melos upgrade:node
  upgrade:node:
    packageFilters:
      scope: [portfolio]
    exec: npm update --save
  serve:
    packageFilters:
      scope: [portfolio]
    exec: npx concurrently "npm run watch" "jaspr serve --verbose"; npm run clean
  start:
    packageFilters:
      scope: [portfolio]
    exec: npm run start
