name: portfolio_workspace
repository: https://github.com/siesdart/jaspr-portfolio

command:
  clean:
    hooks:
      pre: |
        melos clean:jaspr

packages:
  - apps/**
  - packages/**

scripts:
  build:
    packageFilters:
      scope: [portfolio]
    exec: jaspr build
  build:dart:
    packageFilters:
      dependsOn: build_runner
    run: |
      melos exec --depends-on=build_runner -- "dart run build_runner build --delete-conflicting-outputs"
  clean:jaspr:
    packageFilters:
      scope: [portfolio]
    exec: jaspr clean
  outdated:
    exec: dart pub outdated --no-dev-dependencies --up-to-date --no-dependency-overrides
  upgrade:
    exec: dart pub upgrade --major-versions
  serve:
    packageFilters:
      scope: [portfolio]
    exec: jaspr serve
  start:
    packageFilters:
      scope: [portfolio]
    run: |
      serve apps/portfolio/build/jaspr
