name: portfolio_workspace
repository: https://github.com/siesdart/jaspr-portfolio

packages:
  - apps/**
  - packages/**

scripts:
  analyze:
    exec: dart analyze .
  build:
    packageFilters:
      dependsOn: build_runner
    run: |
      melos exec --depends-on=build_runner -- "dart run build_runner build --delete-conflicting-outputs"
  outdated:
    exec: dart pub outdated --show-all
  upgrade:
    exec: dart pub upgrade --major-versions
  serve:
    packageFilters:
      scope: [portfolio]
    run: |
      serve apps/portfolio/build/jaspr
