name: common
description: common
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  dart_mappable: ^4.5.0
  jaspr: ^0.20.0
  jaspr_router: ^0.7.1

dev_dependencies:
  build_runner: ^2.5.4
  dart_mappable_builder: ^4.5.0
  very_good_analysis: ^9.0.0
