name: common
description: common
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.19.0
  dart_mappable: ^4.2.2
  jaspr: ^0.13.3

dev_dependencies:
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.2.3
  very_good_analysis: ^6.0.0
