name: common
description: common
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  dart_mappable: ^4.3.0
  jaspr: ^0.17.0
  jaspr_router: ^0.6.1

dev_dependencies:
  build_runner: ^2.4.14
  dart_mappable_builder: ^4.3.0
  very_good_analysis: ^7.0.0
