name: common
description: common
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.19.0
  dart_mappable: ^4.2.2
  jaspr: ^0.14.0
  jaspr_router: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.12
  dart_mappable_builder: ^4.2.3
  very_good_analysis: ^6.0.0
