include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - lib/generated/**
    - lib/**.g.dart
    - lib/**.init.dart
    - lib/**.imports.dart
    - lib/**.mapper.dart
    - lib/jaspr_options.dart

linter:
  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    require_trailing_commas: false
