include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - lib/generated/**
    - lib/**.g.dart
    - lib/**.init.dart
    - lib/**.imports.dart
    - lib/**.mapper.dart
    - lib/jaspr_options.dart
  plugins:
    - custom_lint

linter:
  rules:
    always_use_package_imports: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
